site_name: Urban Guidelines
theme:
  name: material
  palette:
    primary: 'red'
    accent: 'red'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - pymdownx.details

# Pages Tree
pages:
- Home: index.md
- About the guidelines: 'about.md'
- 'Mega Projects':
  - 'Mega Projects': 'mega.md'
- 'Major Subdivisions':
  - 'Major Subdivisions': 'major.md'
- 'Waterfront':
  - 'Introduction': 'waterfront\Introduction.md'
  - 'Mixed-use Developments': 'waterfront\Favour-mixed-use-development.md'
  - 'Public Access': 'waterfront\Ensure-public-access-to-the-waterfront.md'
  - 'Stage the WaterFront': 'waterfront\Stage-the-waterfront.md'
  - 'Sustainability': 'waterfront\Stage-the-waterfront.md'
- 'Green':
  - Lorem: 'green.md'
  - Lorem: 'green.md'
- 'Heritage':
  - Lorem: 'heritage.md'
  - Lorem: 'heritage.md'
