site_name: My Docs
theme:
  name: material
  palette:
    primary: 'red'
    accent: 'red'

markdown_extensions:
  - admonition
  - pymdownx.details

# Pages Tree
pages:
- Home: 'index.md'
- About: 'about.md'
- Assets:
    - 'Waterfront':
      - 'Introduction': 'assets\waterfront\Introduction.md'
      - 'Mixed-use Developments': 'assets\waterfront\Favour-mixed-use-development.md'
      - 'Public Access': 'assets\waterfront\Ensure-public-access-to-the-waterfront.md'
      - 'Stage the WaterFront': 'assets\waterfront\Stage-the-waterfront.md'
      - 'Sustainability': 'assets\waterfront\Stage-the-waterfront.md'
    - 'Green': 'assets/waterfront.md'
    - 'Heritage': 'assets/waterfront.md'
- Projects:
    - 'Mega Projects': 'projects/mega.md'
    - 'Major Subdivisions': 'projects/major.md'
